/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HauntedHouse;

import HauntedHouse.Menu.Menu;

import java.io.IOException;

/**
 * Main Class
 *
 * @author Pedro Machado "pedroma2000"
 */
@Generated
public class App {

    /**
     * Menu instance
     */
    private static Menu menu = new Menu();

    /**
     * Main method
     *
     * @param args main args
     * @throws IOException IOException
     */
    @Generated
    public static void main(String[] args) throws IOException{
        menu.mainMenu();
    }
}