name: Project Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      

  BlackBox_tests:
   
    runs-on: [ubuntu-latest]
    
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: BlackBox tests
        run: ./gradlew test
      - uses: actions/upload-artifact@v1
        with:
          name: BlackBox Test Report
          path: build/reports/tests/test

  WhiteBox_tests:
    
    runs-on: [ubuntu-latest]
    needs: build
    
    steps:
      - uses: actions/checkout@v1
      - name: WhiteBox tests
        run: |
          ./gradlew test
      - uses: actions/upload-artifact@v1
        with:
          name: Jacoco Test Report
          path: build/jacocoHtml

  QA:

    runs-on: [ubuntu-latest]
    needs: [BlackBox_tests, WhiteBox_tests]

    steps:
      - uses: actions/checkout@v1
      - name: PMD report
        run: ./gradlew build
      - uses: actions/upload-artifact@v1
        with:
          name: PMD Report
          path: build/reports/pmd
